// src/components/Experience.vue
<template>
  <v-container
    id="experience"
  >
    <v-responsive class="align-center text-center fill-height">
      <div class="text-h3 mb-10">My Experience</div>
      <v-row class="d-flex align-center justify-center">
        <v-col cols="8">
          <v-row class="d-flex align-center justify-center">
            <v-col cols="6">
              <v-card
                class="mx-auto text-left"
                variant="outlined"
                height="20vh"
              >
                <v-card-title class="text-h5 font-weight-bold pa-3">Vue JS Developer</v-card-title>
                <v-card-text>
                  <div class="mb-3">
                    <span class="text-h6">Questronix Corporation</span><br />
                    <i class="text-grey-darken-3">June 2022 - July 2023</i>
                  </div>
                  <p><strong>Tech:</strong> Vue js, PHP, CodeIgniter, JQuery, MSSQL, Javascript, CSS, Git</p>
                </v-card-text>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="mx-auto text-left"
                variant="outlined"
                height="20vh"
              >
                <v-card-title class="text-h5 font-weight-bold pa-3">Full Stack Web Developer</v-card-title>
                <v-card-text>
                  <div class="mb-3">
                    <span class="text-h6">Quiddity Usability Labs</span><br />
                    <i class="text-grey-darken-3">July 2021 - December 2021</i>
                  </div>
                  <p><strong>Tech:</strong> Vue. js, PHP, Laravel, Drupal, JQuery, MySQL, Javascript, CSS, Git</p>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>

          <v-row class="d-flex align-center justify-center">
            <v-col cols="6">
              <v-card
                class="mx-auto text-left"
                variant="outlined"
                height="20vh"
              >
                <v-card-title class="text-h5 font-weight-bold pa-3">Software Developer</v-card-title>
                <v-card-text>
                  <div class="mb-3">
                    <span class="text-h6">Mobext Philippines</span><br />
                    <i class="text-grey-darken-3">May 2019 - December 2021</i>
                  </div>
                  <p><strong>Tech:</strong> PHP, Laravel, CodeIgniter, Vue js, OctoberCMS, Vuetify, Bootstrap, Docker, Git</p>
                </v-card-text>
              </v-card>
            </v-col>

            <v-col cols="6">
              <v-card
                class="mx-auto text-left"
                variant="outlined"
                height="20vh"
              >
                <v-card-title class="text-h5 font-weight-bold pa-3">Jarvis Butler Property Management Corporation</v-card-title>
                <v-card-text>
                  <div class="mb-3">
                    <span class="text-h6">Junior Web Developer</span><br />
                    <i class="text-grey-darken-3">July 2021 - December 2021</i>
                  </div>
                  <p><strong>Tech:</strong> HTML, CSS, Javascript, PHP, Laravel, Vue js, JQuery, Bootstrap, Git</p>
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
        </v-col>
      </v-row>
    </v-responsive>
  </v-container>
</template>

<script setup>
  //
</script>

// app/components/Experience.tsx
export default function Experience() {
  return (
    <section
      id="experience"
      className="text-amber-50"
    >
      <div className="container mx-auto p-10 flex flex-col gap-24">
        <h2 className="text-lg sm:text-3xl font-bold">Experience</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {/* Experience Card */}
          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Senior Developer - Business Application</h1>
            <p className="text-2xl">Diversified Robotics</p>
            <i className="font-light">January 2024 - April 2025</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <p className="relative bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>Vue.js</span></p>
                <p className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>React</span></p>
                <p className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>Node.js</span></p>
                <p className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>Laravel</span></p>
                <p className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>Azure</span></p>
                <p className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm"><span>Typescript</span></p>
            </div>
          </div>

          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Full-Stack Developer</h1>
            <p className="text-2xl">Redmer Production, LLC</p>
            <i className="font-light">2023</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Vue.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Node.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Javscript</span>
            </div>
          </div>

          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Vue.js Developer</h1>
            <p className="text-2xl">Questronix Corporation</p>
            <i className="font-light">2022 - 2023</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Vue.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Node.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">CodeIgniter</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">SQL</span>
            </div>
          </div>

          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Full-Stack Web Developer</h1>
            <p className="text-2xl">Quiddity Usability Labs</p>
            <i className="font-light">July 2021 - December 2021</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Vue.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Laravel</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Drupal</span>
            </div>
          </div>

          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Software Developer</h1>
            <p className="text-2xl">Mobext Philippines</p>
            <i className="font-light">May 2019 - December 2021</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Vue.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Laravel</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">CodeIgniter</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">MySQL</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Docker</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Javascript</span>
            </div>
          </div>

          <div className="flex flex-col px-5 sm:px-20 gap-4">
            <h1 className="text-3xl font-medium">Junior Web Developer</h1>
            <p className="text-2xl">JARVIS Butler Property Management Corporation</p>
            <i className="font-light">September 2018 - March 2019</i>
            <div className="grid grid-cols-4 gap-1.5 items-center">
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Vue.js</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Laravel</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">MySQL</span>
                <span className="bg-zinc-400 px-2 py-1 rounded-md font-medium text-xs sm:text-sm">Javascript</span>
            </div>
          </div>
        </div>
      </div>
  </section>
  )
}
